// vue-app/src/views/orders/components/orderEntry/OrderEntryCard.vue
<template>
  <v-card :key="entryId">
      <v-card-text>
        <b>{{orderEntry.username}}</b>

        <PaymentStatus :order="order" :order-entry="orderEntry"
                       :current-user-id="currentUserId"></PaymentStatus>


        <template v-for="(dishEntry, dishEntryIndex) in orderEntry.dishEntries">

          <div class="dish-entry-wrapper">
            <div class="dish-entry-index">
              {{dishEntryIndex + 1}}.
            </div>

            <div class="dish-entry-content">
              <template v-if="isEntryEdited === true && dishEntryId === dishEntry.id">
                <edit-order-entry
                    :order-entry="orderEntry"
                    :dish-entry="dishEntry"
                    :key="dishEntry.id">
                </edit-order-entry>

              </template>
              <template v-else>
                <show-order-entry
                    :order-entry="orderEntry"
                    :dish-entry="dishEntry"
                    :current-user-id="currentUserId"
                    :key="dishEntry.id"
                    :index="dishEntryIndex + 1">
                </show-order-entry>

              </template>
            </div>
          </div>

        </template>

        <div class="dish-entry-wrapper" v-if="order.orderState === 'CREATED' && isOrderEntryOwner(orderEntry) && isEntryEdited === false">
          <div class="dish-entry-index">
            {{orderEntry.dishEntries.length + 1}}.
          </div>

          <div class="dish-entry-content">

            <div v-if="isEntryCreating === false">
              <v-btn text color="success" @click="createEntry()">
                Add entry &nbsp;<i class="fa fa-plus" aria-hidden="true"></i>
              </v-btn>
            </div>
            <div v-if="isEntryCreating === true">
              <create-order-entry></create-order-entry>
            </div>
          </div>
        </div>

        <!--<v-divider></v-divider>-->

        <div>
          <b>Cost for user:
            <price :data-price="orderEntry.finalPrice"/>
          </b>
        </div>

      </v-card-text>


  </v-card>
</template>

<script>
  import Price from '../../../commons/PriceElement.vue'
  import CreateOrderEntry from './CreateOrderEntry.vue'
  import EditOrderEntry from './EditOrderEntry.vue'
  import ShowOrderEntry from './ShowOrderEntry.vue'
  import {mapState} from 'vuex'
  import {
    NAMESPACE_MODIFY_ORDER_ENTRY,
    SET_DISH_ENTRY_CREATING,
  } from "../../../../store/modules/ModifyOrderEntryState";
  import PriceSummary from "../PriceSummary";
  import SimpleCard from "../../../commons/SimpleCard";
  import ViewWrapper from "../../../commons/ViewWrapper";
  import PaymentStatus from "../PaymentStatus";

  export default {
    name: "OrderEntryCard",
    props: ["order", "orderEntry", "entryId", "currentUserId"],
    methods: {
      isOrderEntryOwner(orderEntry) {
        return orderEntry.userId === this.currentUserId
      },
      paymentStatus(orderEntry) {
        if (orderEntry.paymentStatus === "UNPAID") {
          return "Unpaid"
        } else if (orderEntry.paymentStatus === "MARKED") {
          return "Marked as paid"
        } else if (orderEntry.paymentStatus === "CONFIRMED") {
          return "Payment confirmed"
        } else {
          return orderEntry.paymentStatus
        }
      },
      createEntry() {
        this.$store.commit(`${NAMESPACE_MODIFY_ORDER_ENTRY}/${SET_DISH_ENTRY_CREATING}`, {})
      },
    },
    computed: {
      ...mapState('modifyOrderEntry', [
        "isEntryCreating",
        "isEntryEdited",
        "orderEntryId",
        "dishEntryId",
      ])
    },
    components: {
      PaymentStatus,
      ViewWrapper,
      SimpleCard,
      PriceSummary,
      Price,
      CreateOrderEntry,
      EditOrderEntry,
      ShowOrderEntry
    }
  }
</script>

<style scoped>
  .dish-entry-wrapper {
    display: flex;
    flex-direction: row;
  }

  .dish-entry-index {
    min-width: 18px;
    height: 36px;
    line-height: 36px;
  }

  .dish-entry-content {

  }
</style>

// frontend-angular/src/app/views/orders/show-order-view/components/order-entries-list/order-entry-card/order-entry-card.component.ts
import {Component, Input} from '@angular/core';
import {ParticipantsOrderEntry, ShowOrderDto} from "../../../../../../../frontend-client";
import {OrderEntryService} from "../../../../../../service/order-entry.service";
import OrderStateEnum = ShowOrderDto.OrderStateEnum;

@Component({
  selector: 'app-order-entry-card',
  templateUrl: './order-entry-card.component.html',
  styleUrls: ['./order-entry-card.component.scss']
})
export class OrderEntryCardComponent {
  @Input() order!: ShowOrderDto;
  @Input() orderEntry!: ParticipantsOrderEntry;
  @Input() entryId!: number;
  @Input() currentUserId!: string;

  constructor(private orderEntryService: OrderEntryService) {
  }

  isOrderEntryOwner() {
    return this.orderEntry.userId === this.currentUserId;
  }

  createEntry() {
    this.orderEntryService.setDishEntryCreating()
  }

  get isEntryCreating() {
    return this.orderEntryService.isModifiedEntryCreating()
  }

  get isEntryEdited() {
    return this.orderEntryService.isModifiedEntryEdited()
  }

  get dishEntryId(): string {
    return this.orderEntryService.getModifiedDishEntryId();
  }

  canAddNewEntry() {
    return this.order.orderState === OrderStateEnum.CREATED && this.isOrderEntryOwner() && !this.isEntryEdited
  }
}

<div>

  <app-title-with-payment-status
    [title]="orderEntry.username"
    [priceForUser]="orderEntry.finalPrice"
    [order]="order"
    [orderEntry]="orderEntry"
    [currentUserId]="currentUserId"
    [costForUser]="orderEntry.finalPrice"
  ></app-title-with-payment-status>

    <div *ngFor="let dishEntry of orderEntry.dishEntries; let dishEntryIndex = index;">
          <div *ngIf="isEntryEdited === true && dishEntryId === dishEntry.id">
<!--            <edit-order-entry-->
<!--              :order-entry="orderEntry"-->
<!--              :dish-entry="dishEntry"-->
<!--              :key="'edit-order-entry-' + dishEntry.id"-->
<!--            >-->
<!--            </edit-order-entry>-->
          </div>
          <div *ngIf="!(isEntryEdited === true && dishEntryId === dishEntry.id)">
            <app-show-order-entry
              [order]="order"
              [orderEntry]="orderEntry"
              [dishEntry]="dishEntry"
              [currentUserId]="currentUserId"
              [index]="dishEntryIndex + 1"
            >
            </app-show-order-entry>
          </div>

      <div *ngIf="dishEntryIndex < orderEntry.dishEntries.length - 1">
        <hr/>
<!--        <v-divider :key="'dish-entry-divider' + dishEntryIndex" class="dishes-divider"></v-divider>-->
      </div>
    </div>

    <div *ngIf="canAddNewEntry()">
          <div *ngIf="isEntryCreating === false">
            <button color="primary ml-4" (click)="createEntry()">
              Add entry<i class="fa fa-plus ml-2" aria-hidden="true"></i>
            </button>
          </div>
          <div *ngIf="isEntryCreating === true">
<!--            <create-order-entry></create-order-entry>-->
          </div>
    </div>
</div>
