// vue-app/src/views/orders/components/PaymentOptionsSummary.vue
<template>
  <div>
    <v-list dense>
      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByCash == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by cash &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByCash == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by cash &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByBankTransfer == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by bank transfer &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByBankTransfer == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by bank transfer &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item v-if="paymentData.paymentByBankTransfer">
        <v-list-item-content>
          <div class="px-3 user-selectable">
            {{ formatBankAccountNr(paymentData.bankTransferNumber) }}
          </div>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByBlik == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by BLIK &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByBlik == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by BLIK &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item v-if="paymentData.paymentByBankTransfer">
        <v-list-item-content>
          <div class="px-3 user-selectable">
            {{ formatBlikPhoneNumber(paymentData.blikPhoneNumber) }}
          </div>
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import {Prop} from "vue-property-decorator";
  import Component from "vue-class-component";
  import {PaymentData} from "../../../frontend-client";

  @Component({})
  export default class PaymentOptionsSummary extends Vue {
    // @Prop() order;
    @Prop() paymentData!: PaymentData;

    formatBankAccountNr(unformattedInput: string) {
      if (unformattedInput) {
        var input = unformattedInput.trim();

        if (input.length === 26) {
          var result = input.slice(0, 2) + " ";

          for (var i = 2; i < input.length; i += 4) {
            result += input.slice(i, i + 4) + " "
          }

          return result;
        }
      }

      return unformattedInput;
    }

    formatBlikPhoneNumber(unformattedInput: string) {
      if (unformattedInput) {
        var input = unformattedInput.trim();

        if (input.length >= 9) {
          return `${input.slice(0, input.length - 6)} ${input.slice(input.length - 6, input.length - 3)} ${input.slice(input.length - 3, input.length)}`
        }
      }

      return unformattedInput;
    }
  }

</script>

<style scoped>
  .user-selectable {
    user-select: text;
  }
</style>

// frontend-angular/src/app/views/orders/show-order-view/components/payment-options-summary/payment-options-summary.component.ts
import {Component, Input} from '@angular/core';
import {PaymentData, ShowOrderResponse} from "../../../../../../frontend-client";
import {faCheck, faTimes} from "@fortawesome/free-solid-svg-icons";

@Component({
  selector: 'app-payment-options-summary',
  templateUrl: './payment-options-summary.component.html',
  styleUrls: ['./payment-options-summary.component.scss']
})
export class PaymentOptionsSummaryComponent {

  @Input() showOrderResponse!: ShowOrderResponse

  faCheck = faCheck
  faTimes = faTimes

  get paymentData() {
    return this.showOrderResponse.order.paymentData
  }

  formatBankAccountNr(unformattedInput: string) {
    if (unformattedInput) {
      const input = unformattedInput.trim();

      if (input.length === 26) {
        let result = input.slice(0, 2) + " ";

        for (let i = 2; i < input.length; i += 4) {
          result += input.slice(i, i + 4) + " ";
        }

        return result;
      }
    }

    return unformattedInput;
  }

  formatBlikPhoneNumber(unformattedInput: string) {
    if (unformattedInput) {
      const input = unformattedInput.trim();

      if (input.length >= 9) {
        return `${input.slice(0, input.length - 6)} ${input.slice(
          input.length - 6,
          input.length - 3
        )} ${input.slice(input.length - 3, input.length)}`;
      }
    }

    return unformattedInput;
  }

}

<div>
  <div class="payment-entry">
    <div class="chip" *ngIf="paymentData.paymentByCash === true" color="green" text-color="white">
      Payment by cash &nbsp; <fa-icon [icon]="faCheck" class="ml-2"></fa-icon>
    </div>
    <div class="chip" *ngIf="paymentData.paymentByCash === false" color="red" text-color="white">
      Payment by cash &nbsp; <fa-icon [icon]="faTimes" class="ml-2"></fa-icon>
    </div>
  </div>
  <div class="payment-entry">
    <div class="chip" *ngIf="paymentData.paymentByBankTransfer === true" color="green" text-color="white">
      Payment by bank transfer <fa-icon [icon]="faCheck" class="ml-2"></fa-icon>
    </div>
    <div class="chip" *ngIf="paymentData.paymentByBankTransfer === false" color="red" text-color="white">
      Payment by bank transfer <fa-icon [icon]="faTimes" class="ml-2"></fa-icon>
    </div>
    <div class="px-3 user-selectable flex" *ngIf="paymentData.paymentByBankTransfer && paymentData.bankTransferNumber != null && paymentData.bankTransferNumber.trim().length > 0">
      {{ formatBankAccountNr(paymentData.bankTransferNumber) }}
      <app-bank-transfer-qrcode [showOrderResponse]="showOrderResponse"></app-bank-transfer-qrcode>
    </div>
  </div>

  <div class="payment-entry">
    <div class="chip" *ngIf="paymentData.paymentByBlik === true" color="green" text-color="white">
      Payment by BLIK &nbsp; <fa-icon [icon]="faCheck" class="ml-2"></fa-icon>
    </div>
    <div class="chip" *ngIf="paymentData.paymentByBlik === false" color="red" text-color="white">
      Payment by BLIK &nbsp; <fa-icon [icon]="faTimes" class="ml-2"></fa-icon>
    </div>
    <div *ngIf="paymentData.paymentByBlik && paymentData.blikPhoneNumber != null && paymentData.blikPhoneNumber.trim().length > 0">
      <div class="px-3 user-selectable">
        {{ formatBlikPhoneNumber(paymentData.blikPhoneNumber) }}
      </div>
    </div>
  </div>
</div>
