// backendApp/vue-app/src/components/orders/OrderStateButtons.vue
<template>
  <div>
    <!-- orderCreatedButton -->
    <button v-if="this.orderState == 'ORDERED' || this.orderState == 'ORDERING'" type="button" class="btn btn-success"
            v-on:click="setAsCreated">
      <i class="fa fa-undo" aria-hidden="true"/>&nbsp;Mark back as un-ordered
    </button>

    <!-- placeOrderButton -->
    <span>
      <a v-if="this.orderState === 'CREATED' || this.orderState === 'ORDERING'"
         v-bind:href="'#/orders/' + this.orderId + '/order_view'">
        <button class="btn btn-success">
          Place order&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"/>
        </button>
      </a>

      <button v-if="this.orderState == 'DELIVERED' || this.orderState == 'REJECTED'" v-on:click="setAsOrdered"
              class="btn btn-success">
        <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Back to ordered
      </button>
    </span>

    <!-- order-delivered-button -->
    <button v-if="this.orderState == 'ORDERED'" type="button" class="btn btn-success" v-on:click="setAsDelivered">
      Mark as delivered&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"/>
    </button>

    <!-- order-rejected-button -->
    <a class="btn btn-danger" v-on:click="setAsRejected">
      Mark as rejected&nbsp;<i class="fa fa-ban" aria-hidden="true"/>
    </a>

    <!-- edit-order-button -->
    <a v-bind:href="'#/orders/' + this.orderId + '/edit'" class="btn btn-light">
      Edit &nbsp;<i class="fa fa-pencil" aria-hidden="true"></i>
    </a>

    <!-- delete-order-button -->
    <a class="btn btn-danger" v-on:click=deleteEntry>
      Delete &nbsp;
      <i class="fa fa-times" aria-hidden="true"></i>
    </a>
  </div>
</template>

<script>
  import OrdersApiConnector from "../../lib/OrdersApiConnector";

  export default {
    name: 'order-state-buttons',
    props: ['orderId', 'orderState'],
    data() {
      return {}
    },
    methods: {
      setAsCreated: function (e) {
        OrdersApiConnector.setOrderAsCreated(this.orderId)
          .then(successResponse => window.location.reload())
          .catch(errResponse => console.log(errResponse));
      },
      setAsOrdered: function (e) {
        OrdersApiConnector.setOrderAsOrdered(this.orderId)
          .then(successResponse => window.location.reload())
          .catch(errResponse => console.log(errResponse));
      },
      setAsDelivered: function (e) {
        OrdersApiConnector.setOrderAsDelivered(this.orderId)
          .then(successResponse => window.location.reload())
          .catch(errResponse => console.log(errResponse));
      },
      setAsRejected: function (e) {
        OrdersApiConnector.setOrderAsRejected(this.orderId)
          .then(successResponse => window.location.reload())
          .catch(errResponse => console.log(errResponse));
      },
      deleteEntry: function (e) {
        OrdersApiConnector.deleteOrder(this.orderId + '/delete')
          .then(successResponse => window.location.href = '#/orders')
          .catch(errResponse => console.log(errResponse));
      },
    }
  }

</script>

// frontend-angular/src/app/views/orders/edit-order-view/components/order-state-buttons/order-state-buttons.component.ts
import {Component, Input} from '@angular/core';
import {OrderControllerService, ShowOrderDto} from "../../../../../../frontend-client";
import OrderStateEnum = ShowOrderDto.OrderStateEnum;
import {Router} from "@angular/router";
import {EMPTY, switchMap, tap} from "rxjs";
import {DialogService} from "../../../../../service/dialog.service";

@Component({
  selector: 'app-order-state-buttons',
  templateUrl: './order-state-buttons.component.html',
  styleUrls: ['./order-state-buttons.component.scss']
})
export class OrderStateButtonsComponent {

  @Input() orderId!: string
  @Input() orderState!: OrderStateEnum

  constructor(private router: Router,
              private orderControllerService: OrderControllerService,
              private dialogService: DialogService) {
  }

  setAsCreated() {
    this.orderControllerService.setAsCreated(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  setAsOrdered() {
    this.orderControllerService.setBackAsOrdered(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  setAsRejected() {
    this.orderControllerService.setAsRejected(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  deleteOrder() {
    this.dialogService.displayDeleteDialog("Delete order?", "Are you sure you want to delete this order?")
      .afterClosed()
      .pipe(
        switchMap(confirmed => {
          if (confirmed) {
            return this.orderControllerService._delete(this.orderId)
              .pipe(
                tap(() => {
                  this.router.navigate(['/orders/all'], {onSameUrlNavigation: "reload"})
                })
              )
          } else {
            return EMPTY;
          }
        })
      )
      .subscribe()
  }
}

<div>
  <app-button
    color="primary"
    *ngIf="this.orderState === 'ORDERED' || this.orderState === 'ORDERING'"
    (click)="setAsCreated()"
  >
    <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Mark back as un-ordered
  </app-button>

  <app-button
    color="primary"
    *ngIf="this.orderState === 'DELIVERED' || this.orderState === 'REJECTED'"
    (click)="setAsOrdered()"
  >
    <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Back to ordered
  </app-button>

  <app-button color="warn" (click)="setAsRejected()">
    Mark as rejected&nbsp;<i class="fa fa-ban" aria-hidden="true"></i>
  </app-button>

  <app-button color="warn" (click)="deleteOrder()">
    Delete &nbsp;<i class="fa fa-times" aria-hidden="true"></i>
  </app-button>
</div>
