// altszama/src/views/orders/components/OrderStateButtons.vue
<template>
  <div>
    <v-btn color="success" v-if="this.orderState === 'ORDERED' || this.orderState === 'ORDERING'" @click="setAsCreated">
      <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Mark back as un-ordered
    </v-btn>

    <v-btn color="success" v-if="this.orderState === 'DELIVERED' || this.orderState === 'REJECTED'"
           @click="setAsOrdered">
      <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Back to ordered
    </v-btn>

    <v-btn color="error" @click="setAsRejected()">
      Mark as rejected&nbsp;<i class="fa fa-ban" aria-hidden="true"></i>
    </v-btn>

    <v-btn color="error" @click=deleteDishEntry()>
      Delete &nbsp;<i class="fa fa-times" aria-hidden="true"></i>
    </v-btn>
  </div>
</template>

<script lang="ts">
  import {
    SET_ORDER_AS_CREATED_ACTION,
    SET_ORDER_AS_ORDERED_ACTION,
    SET_ORDER_AS_DELIVERED_ACTION,
    SET_ORDER_AS_REJECTED_ACTION,
    DELETE_ORDER_ACTION
  } from "../../../store/modules/ShowOrderModule";
  import router from '../../../router'
  import Component from "vue-class-component";
  import Vue from "vue";

  @Component({})
  export default class OrderStateButtons extends Vue {
    longVersion = true;

    get orderId() {
      return this.$store.state.showOrder.order.id;
    }

    get orderState() {
      return this.$store.state.showOrder.order.orderState;
    }

    setAsCreated() {
      return this.$store.dispatch(`showOrder/${SET_ORDER_AS_CREATED_ACTION}`, {orderId: this.orderId});
    }

    setAsOrdered() {
      return this.$store.dispatch(`showOrder/${SET_ORDER_AS_ORDERED_ACTION}`, {orderId: this.orderId});
    }

    setAsDelivered() {
      return this.$store.dispatch(`showOrder/${SET_ORDER_AS_DELIVERED_ACTION}`, {orderId: this.orderId});
    }

    setAsRejected() {
      return this.$store.dispatch(`showOrder/${SET_ORDER_AS_REJECTED_ACTION}`, {orderId: this.orderId});
    }

    deleteDishEntry() {
      return this.$store.dispatch(`showOrder/${DELETE_ORDER_ACTION}`, {orderId: this.orderId});
    }

    placeOrder() {
      router.push("/orders/" + this.orderId + '/order_view')
    }

    edit() {
      router.push("/orders/" + this.orderId + '/edit')
    }
  }

</script>

// frontend-angular/src/app/views/orders/edit-order-view/components/order-state-buttons/order-state-buttons.component.ts
import {Component, Input} from '@angular/core';
import {OrderControllerService, ShowOrderDto} from "../../../../../../frontend-client";
import OrderStateEnum = ShowOrderDto.OrderStateEnum;
import {Router} from "@angular/router";
import {EMPTY, switchMap, tap} from "rxjs";
import {DialogService} from "../../../../../service/dialog.service";

@Component({
  selector: 'app-order-state-buttons',
  templateUrl: './order-state-buttons.component.html',
  styleUrls: ['./order-state-buttons.component.scss']
})
export class OrderStateButtonsComponent {

  @Input() orderId!: string
  @Input() orderState!: OrderStateEnum

  constructor(private router: Router,
              private orderControllerService: OrderControllerService,
              private dialogService: DialogService) {
  }

  setAsCreated() {
    this.orderControllerService.setAsCreated(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  setAsOrdered() {
    this.orderControllerService.setBackAsOrdered(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  setAsRejected() {
    this.orderControllerService.setAsRejected(this.orderId)
      .subscribe({
        next: r => this.router.navigate(["/orders", this.orderId, 'show']),
        error: err => console.log(err)
      })
  }

  deleteOrder() {
    this.dialogService.displayDeleteDialog("Delete order?", "Are you sure you want to delete this order?")
      .afterClosed()
      .pipe(
        switchMap(confirmed => {
          if (confirmed) {
            return this.orderControllerService._delete(this.orderId)
              .pipe(
                tap(() => {
                  this.router.navigate(['/orders/all'], {onSameUrlNavigation: "reload"})
                })
              )
          } else {
            return EMPTY;
          }
        })
      )
      .subscribe()
  }
}

<div>
  <app-button
    color="primary"
    *ngIf="this.orderState === 'ORDERED' || this.orderState === 'ORDERING'"
    (click)="setAsCreated()"
  >
    <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Mark back as un-ordered
  </app-button>

  <app-button
    color="primary"
    *ngIf="this.orderState === 'DELIVERED' || this.orderState === 'REJECTED'"
    (click)="setAsOrdered()"
  >
    <i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Back to ordered
  </app-button>

  <app-button color="warn" (click)="setAsRejected()">
    Mark as rejected&nbsp;<i class="fa fa-ban" aria-hidden="true"></i>
  </app-button>

  <app-button color="warn" (click)="deleteOrder()">
    Delete &nbsp;<i class="fa fa-times" aria-hidden="true"></i>
  </app-button>
</div>
