// frontend-angular/src/app/views/orders/show-order-view/components/price-summary/price-summary.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-price-summary',
  templateUrl: './price-summary.component.html',
  styleUrls: ['./price-summary.component.scss']
})
export class PriceSummaryComponent {
  @Input() orderDecreaseInPercent!: number;
  @Input() orderDeliveryCostPerEverybody!: number;
  @Input() basePriceSum!: number;
  @Input() orderDeliveryCostPerDish!: number;
  @Input() allEatingPeopleCount!: number;
  @Input() totalPrice!: number;
}

<div>
  <div>Base price :</div>
  <div>{{basePriceSum | price}}</div>

  <hr/>

  <div *ngIf="orderDecreaseInPercent === 0 && orderDeliveryCostPerEverybody === 0 && orderDeliveryCostPerDish === 0">
    <div></div>
    <div><span class="unbreakable"><i>No price modifiers</i></span></div>
  </div>

  <div *ngIf="orderDecreaseInPercent !== 0">
    <div>Price decrease :</div>
    <span class="unbreakable">- {{ orderDecreaseInPercent }} %</span>
  </div>

  <div *ngIf="orderDeliveryCostPerEverybody !== 0">
    <div>Delivery :</div>
    <div><span class="unbreakable" >+ {{ orderDeliveryCostPerEverybody | price }}</span></div>
  </div>


  <div *ngIf="orderDeliveryCostPerDish !== 0">
    <div>Delivery per dish:</div>
    <div><span class="unbreakable">+ {{orderDeliveryCostPerDish | price}} * {{ allEatingPeopleCount || 0 }}</span></div>
  </div>

  <hr />

  <div>
    <div>Total:</div>
    <div>{{totalPrice | price}}</div>
  </div>
</div>

// altszama/src/views/orders/components/PriceSummary.vue
<template>
  <div>
    <v-list dense>
      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>Base price :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <price :data-price="basePriceSum"/>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense">
        <v-list-item-content>
          <v-list-item-title>Price decrease :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable">- {{orderDecreaseInPercent}} %</span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense">
        <v-list-item-content>
          <v-list-item-title>Delivery :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable">+ <price :data-price="orderDeliveryCostPerEverybody"/></span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense">
        <v-list-item-content >
          <v-list-item-title>Delivery per dish:</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable">+ <price :data-price="orderDeliveryCostPerDish"/> * {{allEatingPeopleCount}}</span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>Total:</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <price :data-price="totalPrice"/>
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>

<script lang="ts">
  import Price from "@/views/commons/PriceElement.vue"
  import Vue from "vue";
  import Component from "vue-class-component";
  import {Prop} from "vue-property-decorator";

  @Component({
    components: {
      Price,
    }
  })
  export default class PriceSummary extends Vue {
    @Prop() orderDecreaseInPercent!: number;
    @Prop() orderDeliveryCostPerEverybody!: number;
    @Prop() basePriceSum!: number;
    @Prop() orderDeliveryCostPerDish!: number;
    @Prop() allEatingPeopleCount!: number;
    @Prop() totalPrice!: number;
  }
</script>

<style scoped>
  .unbreakable {
    word-break: keep-all;
  }
</style>
