// vue-app/src/components/restaurants/ShowRestaurantDishesTable.vue
<template>
  <div>
    <h4>Dishes</h4>

    <table class="table" v-for="(categoryEntry, i) in this.dishesByCategory" :key="i">
      <thead class="thead">
      <tr>
        <th v-if="categoryEntry.category">
          Category: {{categoryEntry.category}}
        </th>
        <th v-else>
          Uncategorized
        </th>
      </tr>
      </thead>
      <tbody>
      <tr v-for="(dish, j) in categoryEntry.dishes" :key="j">
        <td>
          {{dish.name}} (<price :data-price="dish.price"></price>)

          <v-chip text-color="blue" v-if="dish.lastCrawled != null">
            auto-updated {{ dateToRel(dish.lastCrawled) }}
          </v-chip>
          <v-chip text-color="green" v-if="dish.lastCrawled == null">
            updated manually
          </v-chip>

          <v-btn color="error" @click="deleteDish(dish.id)" class="pull-right">
            Delete&nbsp;<span class="fa fa-times"/>
          </v-btn>

          <v-btn :href="'#/restaurants/' + restaurant.id + '/dishes/' + dish.id + '/edit'" class="pull-right">
            Edit&nbsp;<span class="fa fa-pencil"/>
          </v-btn>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import Price from '../commons/PriceElement'
  import {DELETE_DISH_ACTION} from "../../store/modules/ShowRestaurantState";
  import moment from "moment"

  export default {
    name: "show-restaurant-dishes-table",
    props: ["restaurant", "dishesByCategory"],
    data() {
      return {
        sideDishesShown: false
      }
    },
    methods: {
      deleteDish (dishId) {
        this.$store.dispatch(`showRestaurant/${DELETE_DISH_ACTION}`, {restaurantId: this.restaurant.id, dishId: dishId})
      },
      dateToRel(date) {
        if (date) {
          return moment(date).fromNow()
        } else {
          return ""
        }
      }
    },
    components: {
      Price,
    }
  }
</script>

<style scoped>
  .table td {
    vertical-align: middle;
  }
</style>

// frontend-angular/src/app/views/restaurants/show-restaurant-view/show-restaurant-dishes-table/show-restaurant-dishes-table.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {DishDto, RestaurantDto} from "../../../../../frontend-client";
import * as moment from "moment";


@Component({
  selector: 'app-show-restaurant-dishes-table',
  templateUrl: './show-restaurant-dishes-table.component.html',
  styleUrls: ['./show-restaurant-dishes-table.component.scss']
})
export class ShowRestaurantDishesTableComponent {
  @Input() restaurant!: RestaurantDto;
  @Input() dishesByCategory!: { [key: string]: Array<DishDto> };

  @Output() deleteDish: EventEmitter<string> = new EventEmitter();

  sendDeleteDish(dishId: string) {
    this.deleteDish.emit(dishId)
  }

  dateToRel(date: Date) {
    if (date) {
      return moment(date).fromNow();
    } else {
      return "";
    }
  }
}

<div>
  <div>
    <div *ngFor="let categoryAndDishes of this.dishesByCategory | keyvalue">
      <span *ngIf="categoryAndDishes.key"> Category: {{ categoryAndDishes.key }} </span>
      <span *ngIf="categoryAndDishes.key == null">No category</span>

      <div *ngFor="let dish of categoryAndDishes.value">
        <div>
          {{ dish.name }} ({{dish.price | price}})
        </div>

        <div class="subtitle">
          <span *ngIf="dish.lastCrawled != null">
            auto-updated {{ dateToRel(dish.lastCrawled) }}
          </span>

          <span *ngIf="dish.lastCrawled == null">
            updated manually
          </span>
        </div>

        <span class="edit-buttons">
<!--          <router-link :to="{name: 'DishEditForm', params: {id: restaurant.id, dishId: dish.id}}">-->
<!--            <button text icon class="edit-button">-->
<!--              <i class="fa fa-pencil" aria-hidden="true"></i>-->
<!--            </button>-->
<!--          </router-link>-->

          <button (click)="sendDeleteDish(dish.id)" class="delete-button">
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        </span>
      </div>
    </div>
  </div>
</div>
