// vue-app/src/views/dishes/components/ShowRestaurantDishesTable.vue
<template>
  <div>
    <v-list two-line>
      <template v-for="[category, dishes] in Object.entries(this.dishesByCategory)">
        <v-subheader :key="category">
          <span v-if="category"> Category: {{ category }} </span>
          <span v-else>
            No category
          </span>
        </v-subheader>

        <template v-for="dish in dishes">
          <v-list-item :key="dish.id">
            <v-list-item-content>
              <v-list-item-title>
                {{ dish.name }} (<price :data-price="dish.price"></price>)
              </v-list-item-title>

              <v-list-item-subtitle>
                <span v-if="dish.lastCrawled != null">
                  auto-updated {{ dateToRel(dish.lastCrawled) }}
                </span>

                <span v-if="dish.lastCrawled == null">
                  updated manually
                </span>
              </v-list-item-subtitle>
            </v-list-item-content>

            <v-list-item-action>
              <span class="edit-buttons">
                <router-link :to="{name: 'DishEditForm', params: {id: restaurant.id, dishId: dish.id}}">
                  <v-btn text icon class="edit-button">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                  </v-btn>
                </router-link>

                <v-btn text icon @click="deleteDish(dish.id)" class="delete-button">
                  <i class="fa fa-times" aria-hidden="true"></i>
                </v-btn>
              </span>
            </v-list-item-action>
          </v-list-item>
        </template>
      </template>
    </v-list>
  </div>
</template>

<script lang="ts">
import Price from "../../commons/PriceElement.vue";
import Vue from "vue";
import {Prop} from "vue-property-decorator";
import Component from "vue-class-component";
import {DishDto, RestaurantDto} from "../../../frontend-client";
import moment from "moment";
import DishesApiConnector from "@/lib/api/DishesApiConnector";


@Component({
  components: {
    Price
  }
})
export default class ShowRestaurantDishesTable extends Vue {
  @Prop() restaurant!: RestaurantDto;
  @Prop() dishesByCategory!: { [key: string]: Array<DishDto> };

  connector = new DishesApiConnector()

  deleteDish(dishId: string) {
    this.$emit("delete-dish", dishId)
  }

  dateToRel(date: Date) {
    if (date) {
      return moment(date).fromNow();
    } else {
      return "";
    }
  }
}
</script>

<style scoped>
.table td {
  vertical-align: middle;
}

.edit-buttons {
  margin-left: auto;
}
</style>

// frontend-angular/src/app/views/restaurants/show-restaurant-view/components/show-restaurant-dishes-table/show-restaurant-dishes-table.component.ts
import {Component, Input} from '@angular/core';
import {DishControllerService, DishDto, RestaurantDto} from "../../../../../../frontend-client";
import * as moment from "moment";

import {faPencil, faTimes} from "@fortawesome/free-solid-svg-icons";
import {RestaurantEditorState, RestaurantFormService} from "../../service/restaurant-form.service";
import {EMPTY, switchMap} from "rxjs";
import {DialogService} from "../../../../../service/dialog.service";

@Component({
  selector: 'app-show-restaurant-dishes-table',
  templateUrl: './show-restaurant-dishes-table.component.html',
  styleUrls: ['./show-restaurant-dishes-table.component.scss']
})
export class ShowRestaurantDishesTableComponent {
  @Input() restaurantEditorState!: RestaurantEditorState
  @Input() editedDishId!: string | null;

  @Input() restaurant!: RestaurantDto;
  @Input() dishesByCategory!: { [key: string]: Array<DishDto> };

  RestaurantEditorState = RestaurantEditorState

  faTimes = faTimes
  faPencil = faPencil;


  constructor(private dishControllerService: DishControllerService,
              private restaurantFormService: RestaurantFormService,
              private dialogService: DialogService) {
  }

  onDishDelete(dishId: string) {
    this.dialogService.displayDeleteDialog("Are you sure you want to delete this dish?")
      .afterClosed()
      .pipe(
        switchMap(confirmed => {
          if (confirmed) {
            return this.dishControllerService.deleteDish(dishId)
          } else {
            return EMPTY
          }
        })
      )
      .subscribe(() => {
        this.restaurantFormService.refresh(this.restaurant.id)
      });
  }

  dateToRel(date: Date) {
    if (date) {
      return moment(date).fromNow();
    } else {
      return "";
    }
  }
  onDishEditCancel() {
    this.restaurantFormService.setEditorState(RestaurantEditorState.IDLE)
  }

  onDishEditSucceeded() {
    this.restaurantFormService.refresh(this.restaurant.id)
  }

  setDishAsEdited(dishId: string) {
    this.restaurantFormService.setDishAsEdited(dishId)
  }
}

<div *ngFor="let categoryAndDishes of this.dishesByCategory | keyvalue" class="dish-entry-container">
  <span *ngIf="categoryAndDishes.key" class="text-gray-400"> Category: {{ categoryAndDishes.key }} </span>
  <span *ngIf="categoryAndDishes.key == null" class="text-gray-400">No category</span>

  <div *ngFor="let dish of categoryAndDishes.value" class="dish-entry">
    <div *ngIf="restaurantEditorState == RestaurantEditorState.EDITING_DISH && editedDishId == dish.id">
      <app-edit-dish-form [restaurantId]="restaurant.id" [dishId]="dish.id" (editCancelled)="onDishEditCancel()"
                          (editSucceded)="onDishEditSucceeded()"></app-edit-dish-form>
    </div>

    <div *ngIf="restaurantEditorState != RestaurantEditorState.EDITING_DISH || editedDishId != dish.id">
      <div>
        {{ dish.name }} ({{dish.price | price}})
      </div>

      <div class="subtitle text-gray-400">
            <span *ngIf="dish.lastCrawled != null">
              auto-updated {{ dateToRel(dish.lastCrawled) }}
            </span>

        <span *ngIf="dish.lastCrawled == null">
              updated manually
            </span>
      </div>
    </div>

    <div class="edit-buttons">
      <button mat-button color="primary" (click)="setDishAsEdited(dish.id)">
        <fa-icon [icon]="faPencil"></fa-icon>
      </button>

      <button mat-button (click)="onDishDelete(dish.id)" color="warn">
        <fa-icon [icon]="faTimes" aria-hidden="true"></fa-icon>
      </button>
    </div>
  </div>
</div>
