// frontend-angular/src/app/views/orders/show-order-view/components/order-details/components/price-summary/price-summary.component.ts
import {Component, Input} from '@angular/core';
import {PriceSummaryData} from "../../../../lib/model";

@Component({
  selector: 'app-price-summary',
  templateUrl: './price-summary.component.html',
  styleUrls: ['./price-summary.component.scss']
})
export class PriceSummaryComponent {
  @Input() priceSummaryData!: PriceSummaryData
}

<mat-list>
  <mat-list-item>
    <div matListItemTitle>Base price:</div>
    <div matListItemLine>{{priceSummaryData.basePriceSum | price}}</div>
  </mat-list-item>

  <mat-list-item
    *ngIf="priceSummaryData.deliveryData.decreaseInPercent === 0 && priceSummaryData.deliveryData.deliveryCostPerEverybody === 0 && priceSummaryData.deliveryData.deliveryCostPerDish === 0">
    <div matListItemLine>No price modifiers</div>
  </mat-list-item>

  <mat-list-item *ngIf="priceSummaryData.deliveryData.decreaseInPercent !== 0">
    <div matListItemTitle>Price decrease:</div>
    <div matListItemLine>- {{ priceSummaryData.deliveryData.decreaseInPercent }} %</div>
  </mat-list-item>

  <mat-list-item *ngIf="priceSummaryData.deliveryData.deliveryCostPerEverybody !== 0">
    <div matListItemTitle>Delivery (once):</div>
    <div matListItemLine>
      <span class="unbreakable">+ {{ priceSummaryData.deliveryData.deliveryCostPerEverybody | price }}</span>
    </div>
  </mat-list-item>

  <mat-list-item *ngIf="priceSummaryData.deliveryData.deliveryCostPerDish !== 0">
    <div matListItemTitle>Delivery per dish:</div>
    <div matListItemLine>
        <span class="unbreakable">
          + {{priceSummaryData.deliveryData.deliveryCostPerDish | price}}
          * {{ priceSummaryData.allEatingPeopleCount || 0 }}
        </span>
    </div>
  </mat-list-item>

  <mat-divider></mat-divider>

  <mat-list-item>
    <div matListItemTitle><b>Total:</b></div>
    <div matListItemLine>
      {{priceSummaryData.totalPrice | price}}
    </div>
  </mat-list-item>
</mat-list>

// vue-app/src/views/orders/components/PriceSummary.vue
<template>
  <div>
    <v-list dense>
      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>Base price :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <price :data-price="basePriceSum" />
        </v-list-item-content>
      </v-list-item>

      <v-divider></v-divider>

      <v-list-item class="item-dense" v-if="orderDecreaseInPercent === 0 && orderDeliveryCostPerEverybody === 0 && orderDeliveryCostPerDish === 0">
        <v-list-item-content>
          <v-list-item-title></v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable"><i>No price modifiers</i></span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense" v-if="orderDecreaseInPercent !== 0">
        <v-list-item-content>
          <v-list-item-title>Price decrease :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable">- {{ orderDecreaseInPercent }} %</span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense" v-if="orderDeliveryCostPerEverybody !== 0">
        <v-list-item-content>
          <v-list-item-title>Delivery :</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable" >+ <price :data-price="orderDeliveryCostPerEverybody"/></span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="item-dense" v-if="orderDeliveryCostPerDish !== 0">
        <v-list-item-content>
          <v-list-item-title>Delivery per dish:</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <span class="unbreakable">+ <price :data-price="orderDeliveryCostPerDish" /> * {{ allEatingPeopleCount || 0 }}</span>
        </v-list-item-content>
      </v-list-item>

      <v-divider></v-divider>

      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>Total:</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <price :data-price="totalPrice" />
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>

<script lang="ts">
import Price from "@/views/commons/PriceElement.vue";
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

@Component({
  components: {
    Price
  }
})
export default class PriceSummary extends Vue {
  @Prop() orderDecreaseInPercent!: number;
  @Prop() orderDeliveryCostPerEverybody!: number;
  @Prop() basePriceSum!: number;
  @Prop() orderDeliveryCostPerDish!: number;
  @Prop() allEatingPeopleCount!: number;
  @Prop() totalPrice!: number;
}
</script>

<style scoped>
.unbreakable {
  word-break: keep-all;
}
</style>
