// frontend-angular/src/app/views/orders/show-order-view/components/price-summary/price-summary.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-price-summary',
  templateUrl: './price-summary.component.html',
  styleUrls: ['./price-summary.component.scss']
})
export class PriceSummaryComponent {
  @Input() orderDecreaseInPercent!: number;
  @Input() orderDeliveryCostPerEverybody!: number;
  @Input() basePriceSum!: number;
  @Input() orderDeliveryCostPerDish!: number;
  @Input() allEatingPeopleCount!: number;
  @Input() totalPrice!: number;
}

<div>
  <div>Base price :</div>
  <div>{{basePriceSum | price}}</div>

  <hr/>

  <div *ngIf="orderDecreaseInPercent === 0 && orderDeliveryCostPerEverybody === 0 && orderDeliveryCostPerDish === 0">
    <div></div>
    <div><span class="unbreakable"><i>No price modifiers</i></span></div>
  </div>

  <div *ngIf="orderDecreaseInPercent !== 0">
    <div>Price decrease :</div>
    <span class="unbreakable">- {{ orderDecreaseInPercent }} %</span>
  </div>

  <div *ngIf="orderDeliveryCostPerEverybody !== 0">
    <div>Delivery :</div>
    <div><span class="unbreakable" >+ {{ orderDeliveryCostPerEverybody | price }}</span></div>
  </div>


  <div *ngIf="orderDeliveryCostPerDish !== 0">
    <div>Delivery per dish:</div>
    <div><span class="unbreakable">+ {{orderDeliveryCostPerDish | price}} * {{ allEatingPeopleCount || 0 }}</span></div>
  </div>

  <hr />

  <div>
    <div>Total:</div>
    <div>{{totalPrice | price}}</div>
  </div>
</div>

// vue-app/src/views/orders/components/PriceSummary.vue
<template>
  <div>
    <h3>Price summary</h3>

    <dt v-if="orderDecreaseInPercent !== 0 || orderDeliveryCostPerEverybody !== 0">
      Base price :
    </dt>
    <dd v-if="orderDecreaseInPercent !== 0 || orderDeliveryCostPerEverybody !== 0">
      <price :data-price="basePriceSum"/>
    </dd>

    <dt v-if="orderDecreaseInPercent !== 0">
      Price decrease :
    </dt>
    <dd v-if="orderDecreaseInPercent !== 0">
      - {{orderDecreaseInPercent}} %
    </dd>

    <dt v-if="orderDeliveryCostPerEverybody !== 0">
      Delivery :
    </dt>
    <dd v-if="orderDeliveryCostPerEverybody !== 0">
      + <price :data-price="orderDeliveryCostPerEverybody"/>
    </dd>

    <dt v-if="orderDeliveryCostPerDish !== 0">
      Delivery per dish:
    </dt>
    <dd v-if="orderDeliveryCostPerDish !== 0">
      + <price :data-price="orderDeliveryCostPerDish"/> * {{allEatingPeopleCount}}
    </dd>

    <dt>Total:</dt>
    <dd><b><price :data-price="totalPrice"/></b></dd>
  </div>
</template>

<script>
    import SimpleCard from "../../commons/SimpleCard";
    import Price from "../../commons/PriceElement"
    import ErrorsComponent from '../../commons/Errors'

    export default {
        name: "PriceSummary",
        props: [
            "orderDecreaseInPercent",
            "orderDeliveryCostPerEverybody",
            "basePriceSum",
            "orderDeliveryCostPerDish",
            "allEatingPeopleCount",
            "totalPrice"
        ],
        components: {
            SimpleCard,
            Price,
            ErrorsComponent
        }
    }
</script>

<style scoped>

</style>
