// vue-app/src/views/orders/components/OrderDataSummary.vue
<template>
  <div>
    <v-list dense>
      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>
            Who will order?
          </v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          <div class="text-no-wrap">
            {{ this.order.orderCreatorUsername }}
          </div>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>When?</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          {{ this.order.timeOfOrder }}
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <v-list-item-title>When it'll arrive?</v-list-item-title>
        </v-list-item-content>

        <v-list-item-content>
          {{ this.timeOfDeliveryOrNA() }}
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Prop } from 'vue-property-decorator';
import Component from 'vue-class-component';
import { ShowOrderDto } from '../../../frontend-client';

@Component({})
export default class OrderDataSummary extends Vue {
  @Prop() order!: ShowOrderDto;

  timeOfDeliveryOrNA() {
    if (this.order.timeOfDelivery != null) {
      return this.order.timeOfDelivery;
    }
    return 'As ASAP as possible';
  }
}
</script>

<style scoped>
</style>

// frontend-angular/src/app/views/orders/show-order-view/components/order-data-summary/order-data-summary.component.ts
import {Component, Input} from '@angular/core';
import {OrderEntryDto, ShowOrderDto} from "../../../../../../frontend-client";

@Component({
  selector: 'app-order-data-summary',
  templateUrl: './order-data-summary.component.html',
  styleUrls: ['./order-data-summary.component.scss']
})
export class OrderDataSummaryComponent {
  @Input() order!: ShowOrderDto

  timeOfDeliveryOrNA() {
    if (this.order.timeOfDelivery != null) {
      return this.order.timeOfDelivery;
    } else {
      return "As ASAP as possible";
    }
  }
}

<mat-list>
  <mat-list-item>
    <div matListItemTitle>Who will order?</div>
    <div matListItemLine class="text-no-wrap">
      {{ this.order.orderCreatorUsername }}
    </div>
  </mat-list-item>

  <mat-list-item>
    <div matListItemTitle>When?</div>
    <div matListItemLine class="text-no-wrap">
      {{ this.order.timeOfOrder }}
    </div>
  </mat-list-item>

  <mat-list-item>
    <div matListItemTitle>When it'll arrive?</div>
    <div matListItemLine class="text-no-wrap">
      {{ this.timeOfDeliveryOrNA() }}
    </div>
  </mat-list-item>
</mat-list>
