// frontend-angular/src/app/views/orders/show-order-view/components/order-entries-list/components/create-order-entry/create-order-entry.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {of} from "rxjs";
import {
  OrderEntryControllerService,
  OrderEntrySaveRequest,
  ShowOrderResponse
} from "../../../../../../../../frontend-client";
import {ModifyOrderEntryState, ShowOrderViewService} from "../../../../service/show-order-view.service";
import {FormBuilder} from "@angular/forms";

@Component({
  selector: 'app-create-order-entry',
  templateUrl: './create-order-entry.component.html',
  styleUrls: ['./create-order-entry.component.scss']
})
export class CreateOrderEntryComponent implements OnInit {

  @Input() orderResponse!: ShowOrderResponse
  @Input() modifyOrderEntryState!: ModifyOrderEntryState

  formGroup = this.fb.nonNullable.group({
    name: "",
    price: 0,
    additionalComments: ""
  })

  constructor(private showOrderViewService: ShowOrderViewService,
              private orderEntryControllerService: OrderEntryControllerService,
              private fb: FormBuilder) {
    this.showOrderViewService.setEntryLoading(true)
  }

  ngOnInit() {
    // this.$store.commit("clearErrors");

    const orderId = this.orderResponse.order.id;

    let dishId;
    if (this.orderResponse.allDishesInRestaurant.length > 0) {
      dishId = this.orderResponse.allDishesInRestaurant[0].id;
    } else {
      dishId = null;
    }

    this.showOrderViewService.setInitialCreateOrderEntry({orderId: orderId, dishId: dishId})
    this.showOrderViewService.setEntryLoading(false)
  }

  submitForm() {
    // Set timeout is necessary to properly handle last-minute updates in form controls
    setTimeout(() => this.saveOrderEntry(), 0)
  }

  private saveOrderEntry() {
    let orderEntryToSave: OrderEntrySaveRequest
    orderEntryToSave = {
      orderId: this.orderResponse.order.id,
      dishId: "",
      additionalComments: this.formGroup.controls.additionalComments.value,
      newDish: true,
      newDishName: this.formGroup.controls.name.value,
      newDishPrice: this.formGroup.controls.price.value,
      sideDishes: [],
    };

    // TODO(konkit): add autosuggest
    // TODO(konkit): add detecting already selected dish, thus deduplicating

    this.showOrderViewService.saveOrderEntry(orderEntryToSave)
      .subscribe({
        next: () => {},
        error: error => {
          this.formGroup.setErrors(error)
          return of("")
        }
      })
  }

  cancelEdit() {
    this.showOrderViewService.cancelDishEntryModification()
  }
}

<div>
  <form [formGroup]="formGroup">
    <mat-error>{{formGroup.errors}}</mat-error>

    <div>
      <div class="d-flex fix-top-margin">
        <mat-form-field class="w-full">
          <mat-label>Dish</mat-label>
          <input matInput [formControl]="formGroup.controls.dish" [matAutocomplete]="auto" />

          <mat-autocomplete #auto="matAutocomplete" (optionSelected)='onDishSelected($event.option.value)' [displayWith]="displayFn">
            <mat-option *ngFor="let dish of filteredDishes | async" [value]="dish">
              <div>{{dish.name}}</div>
              <div class="subtitle">
                Price: {{dish.price | price}}, auto-updated {{ dish.lastCrawled | relativeDate }}
              </div>
            </mat-option>
          </mat-autocomplete>
        </mat-form-field>

        <mat-form-field>
          <mat-label>Price</mat-label>
          <app-money-input [formControl]="formGroup.controls.price"></app-money-input>
        </mat-form-field>
      </div>

      <div>Side dishes:</div>

      <!--  <side-dishes-input :chosen-side-dishes="orderEntryData.dishData.chosenSideDishes"-->
      <!--                     :available-side-dishes="availableSideDishes"-->
      <!--                     @change="updateChosenSideDishes($event)">-->
      <!--  </side-dishes-input>-->

      <mat-form-field>
        <mat-label>Additional Comments</mat-label>
        <textarea matInput [formControl]="formGroup.controls.additionalComments"></textarea>
      </mat-form-field>
    </div>

    <hr/>

    <app-button color="primary" (click)="submitForm()">Submit</app-button>
    <app-button (click)="cancelEdit()">Cancel</app-button>
  </form>
</div>

// vue-app/src/views/orders/components/orderEntry/CreateOrderEntry.vue
<template>
  <div>
    <template v-if="this.loadingEntry === false">
      <errors-component/>

      <div>
        <order-entry-form :all-dishes-in-restaurant="allDishesInRestaurant"
                          :all-dishes-by-category="allDishesByCategory"
                          :dish-id-to-side-dishes-map="dishIdToSideDishesMap"
                          :order-entry-data="orderEntryData"
                          @change="updateOrderEntryData($event)">
        </order-entry-form>

        <v-spacer></v-spacer>

        <v-btn color="primary" @click="submitForm()">Submit</v-btn>
        <v-btn @click="cancelEdit()">Cancel</v-btn>
      </div>
    </template>

    <template v-if="this.loadingEntry === true">
      <div class="justify-content-center">
        <spinner></spinner>
      </div>
    </template>
  </div>
</template>

<script lang="ts">
import Component from 'vue-class-component';
import Vue from 'vue';
import ErrorsComponent from '../../../commons/ErrorsComponent.vue';
import Spinner from '../../../commons/Spinner.vue';

import OrderEntryForm from './orderEntryForm/OrderEntryForm.vue';
import { NewDishData, OrderEntryData } from '@/store/modules/ModifyOrderEntryModule';
import { ShowOrderState } from '@/store/modules/ShowOrderModule';
import ErrorHandler from '@/lib/ErrorHandler';
import OrdersApiConnector, { OrderEntryToModify } from '@/lib/api/OrdersApiConnector';
import { DishDto, SideDish } from '@/frontend-client';

@Component({
  components: {
    ErrorsComponent,
    Spinner,
    OrderEntryForm,
  },
})
export default class CreateOrderEntry extends Vue {
  ordersConnector = new OrdersApiConnector()

  created() {
    this.$store.commit('modifyOrderEntry/setEntryLoading', true);
  }

  mounted() {
    this.$store.commit('clearErrors');

    const showOrderState = this.$store.state.showOrder as ShowOrderState;

    const orderId = showOrderState.order.id;

    let dishId;
    if (showOrderState.allDishesInRestaurant.length > 0) {
      dishId = showOrderState.allDishesInRestaurant[0].id;
    } else {
      dishId = null;
    }

    this.$store.commit('modifyOrderEntry/setInitialCreateOrderEntry', { orderId, dishId });
    this.$store.commit('modifyOrderEntry/setEntryLoading', false);
  }

  submitForm() {
    // Set timeout is necessary to properly handle last-minute updates in form controls
    setTimeout(() => this.saveOrderEntry(), 0);
  }

  private saveOrderEntry() {
    const state = this.$store.state.modifyOrderEntry;

    const orderId = state.orderId;

    let orderEntryToSave: OrderEntryToModify;
    if (state.orderEntryData.dishData.kind === 'NewDishData') {
      orderEntryToSave = {
        orderId: state.orderId,
        dishEntryId: state.dishEntryId,
        dishId: '',
        additionalComments: state.orderEntryData.additionalComments,
        newDish: true,
        newDishName: state.orderEntryData.dishData.newDishName,
        newDishPrice: state.orderEntryData.dishData.newDishPrice,
        chosenSideDishes: state.orderEntryData.dishData.chosenSideDishes,
      };
    } else {
      orderEntryToSave = {
        orderId: state.orderId,
        dishEntryId: state.dishEntryId,
        dishId: state.orderEntryData.dishData.dishId,
        additionalComments: state.orderEntryData.additionalComments,
        newDish: false,
        newDishName: '',
        newDishPrice: 0,
        chosenSideDishes: state.orderEntryData.dishData.chosenSideDishes,
      };
    }

    this.ordersConnector
      .saveOrderEntry(orderId, orderEntryToSave)
      .then(() => {
        this.$store.commit('setLoadingTrue');
        this.$store.commit('modifyOrderEntry/cancelDishEntryModification', {});
        this.$store.dispatch('showOrder/fetchOrderDataAction', orderId);
      })
      .catch((errResponse) => ErrorHandler.handleError(errResponse));
  }

  cancelEdit() {
    this.$store.commit('modifyOrderEntry/cancelDishEntryModification', {});
  }

  get allDishesInRestaurant(): DishDto[] {
    return this.$store.state.showOrder.allDishesInRestaurant;
  }

  get loadingEntry() {
    return this.$store.state.modifyOrderEntry.loadingEntry;
  }

  get orderEntryData(): OrderEntryData {
    return this.$store.state.modifyOrderEntry.orderEntryData;
  }

  get allDishesByCategory(): { [category: string]: DishDto[] } {
    return this.$store.state.showOrder.allDishesByCategory;
  }

  get dishIdToSideDishesMap(): { [key: string]: SideDish[] } {
    return this.$store.state.showOrder.dishIdToSideDishesMap;
  }

  updateOrderEntryData(newOrderEntryData: OrderEntryData) {
    this.$store.commit('modifyOrderEntry/updateOrderEntryData', newOrderEntryData);
  }
}
</script>

<style scoped></style>
