// vue-app/src/views/orders/components/PaymentOptionsSummary.vue
<template>
  <div>
    <v-list dense>
      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByCash == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by cash &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByCash == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by cash &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByBankTransfer == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by bank transfer &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByBankTransfer == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by bank transfer &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item v-if="paymentData.paymentByBankTransfer">
        <v-list-item-content>
          <div class="px-3 user-selectable">
            {{ formatBankAccountNr(paymentData.bankTransferNumber) }}
          </div>
        </v-list-item-content>
      </v-list-item>

      <v-list-item>
        <v-list-item-content>
          <span v-if="paymentData.paymentByBlik == true" class="payment-entry">
            <v-chip color="green" text-color="white">
              Payment by BLIK &nbsp; <span class="fa fa-check"></span>
            </v-chip>
          </span>
          <span v-if="paymentData.paymentByBlik == false" class="payment-entry">
            <v-chip color="red" text-color="white">
              Payment by BLIK &nbsp; <span class="fa fa-times"></span>
            </v-chip>
          </span>
        </v-list-item-content>
      </v-list-item>

      <v-list-item v-if="paymentData.paymentByBankTransfer">
        <v-list-item-content>
          <div class="px-3 user-selectable">
            {{ formatBlikPhoneNumber(paymentData.blikPhoneNumber) }}
          </div>
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import {Prop} from "vue-property-decorator";
  import Component from "vue-class-component";
  import {PaymentData} from "../../../frontend-client";

  @Component({})
  export default class PaymentOptionsSummary extends Vue {
    // @Prop() order;
    @Prop() paymentData!: PaymentData;

    formatBankAccountNr(unformattedInput: string) {
      if (unformattedInput) {
        var input = unformattedInput.trim();

        if (input.length === 26) {
          var result = input.slice(0, 2) + " ";

          for (var i = 2; i < input.length; i += 4) {
            result += input.slice(i, i + 4) + " "
          }

          return result;
        }
      }

      return unformattedInput;
    }

    formatBlikPhoneNumber(unformattedInput: string) {
      if (unformattedInput) {
        var input = unformattedInput.trim();

        if (input.length >= 9) {
          return `${input.slice(0, input.length - 6)} ${input.slice(input.length - 6, input.length - 3)} ${input.slice(input.length - 3, input.length)}`
        }
      }

      return unformattedInput;
    }
  }

</script>

<style scoped>
  .user-selectable {
    user-select: text;
  }
</style>

// frontend-angular/src/app/views/orders/show-order-view/components/order-details/components/payment-options-summary/payment-options-summary.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {ParticipantsOrderEntry, PaymentData} from "../../../../../../../../frontend-client";
import {PaymentOptionsData} from "../../../../../lib/model";
import {ShowOrderViewService} from "../../../../service/show-order-view.service";
import {MatTooltipModule} from '@angular/material/tooltip';
import {MatIconModule} from '@angular/material/icon';

import {MatListModule} from '@angular/material/list';

@Component({
    selector: 'app-payment-options-summary',
    templateUrl: './payment-options-summary.component.html',
    styleUrls: ['./payment-options-summary.component.scss'],
    standalone: true,
    imports: [MatListModule, MatIconModule, MatTooltipModule]
})
export class PaymentOptionsSummaryComponent implements OnInit {

  @Input() paymentData!: PaymentData
  @Input() yourOrderEntries!: ParticipantsOrderEntry[]
  @Input() paymentOptionsData!: PaymentOptionsData

  shouldShowQRCodeButton: any;

  constructor(private showOrderViewService: ShowOrderViewService) {
  }

  ngOnInit() {
    this.shouldShowQRCodeButton = this.paymentOptionsData.shouldShowQRCodeButton
  }


  formatBankAccountNr(unformattedInput: string) {
    if (unformattedInput) {
      const input = unformattedInput.trim();

      if (input.length === 26) {
        let result = input.slice(0, 2) + " ";

        for (let i = 2; i < input.length; i += 4) {
          result += input.slice(i, i + 4) + " ";
        }

        return result;
      }
    }

    return unformattedInput;
  }

  formatBlikPhoneNumber(unformattedInput: string) {
    if (unformattedInput) {
      const input = unformattedInput.trim();

      if (input.length >= 9) {
        return `${input.slice(0, input.length - 6)} ${input.slice(
          input.length - 6,
          input.length - 3
        )} ${input.slice(input.length - 3, input.length)}`;
      }
    }

    return unformattedInput;
  }

  showQrModal() {
    this.showOrderViewService.showQrModal()
  }
}

<mat-list>
  @if (paymentData.paymentByCash === true) {
    <mat-list-item>
      <div matListItemTitle>Payment by cash</div>
      <div matListItemLine>Allowed</div>
    </mat-list-item>
  }

  @if (paymentData.paymentByCash === false) {
    <mat-list-item>
      <div matListItemTitle class="flex items-center">Payment by cash</div>
      <div matListItemLine>Not allowed</div>
    </mat-list-item>
  }

  @if (paymentData.paymentByBankTransfer === true) {
    <mat-list-item>
      <div matListItemTitle>Payment by bank transfer</div>
      @if (paymentData.paymentByBankTransfer && paymentData.bankTransferNumber != null && paymentData.bankTransferNumber.trim().length > 0) {
        <div matListItemLine class="user-selectable"
          >
          <span class="text-body2">{{ formatBankAccountNr(paymentData.bankTransferNumber) }}</span>
          @if (shouldShowQRCodeButton) {
            <mat-icon
              (click)="showQrModal()" class="cursor-pointer ml-2 material-icons-outlined"
              matTooltip="Show QR code for bank transfer">qr_code
            </mat-icon>
          }
        </div>
      }
    </mat-list-item>
  }

  @if (paymentData.paymentByBankTransfer === false) {
    <mat-list-item>
      <div matListItemTitle>Payment by bank transfer</div>
      <div matListItemLine>Not allowed</div>
    </mat-list-item>
  }

  @if (paymentData.paymentByBlik === true) {
    <mat-list-item>
      <div matListItemTitle>Payment by BLIK</div>
      @if (paymentData.paymentByBlik && paymentData.blikPhoneNumber != null && paymentData.blikPhoneNumber.trim().length > 0) {
        <div matListItemLine class="user-selectable"
          >
          <span class="text-body2">{{ formatBlikPhoneNumber(paymentData.blikPhoneNumber) }}</span>
        </div>
      }
    </mat-list-item>
  }

  @if (paymentData.paymentByBlik === false) {
    <mat-list-item>
      <div matListItemTitle>Payment by BLIK</div>
      <div matListItemLine>Not allowed</div>
    </mat-list-item>
  }

</mat-list>
